version: '3.5'

services:
  # Redis service
  redis:
    image: redis:latest
    container_name: zabbix-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass my_redis_password
    volumes:
      - redis_data:/data

  # Zabbix server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    restart: always
    depends_on:
      - postgres
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
      ZBX_REDIS_HOST: redis
      ZBX_REDIS_PORT: 6379
      ZBX_REDIS_PASSWORD: my_redis_password
    ports:
      - "10051:10051"

  # PostgreSQL database for Zabbix
  postgres:
    image: postgres:15
    container_name: zabbix-postgres
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Zabbix web interface
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    restart: always
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "UTC"
    ports:
      - "8080:8080"

  # Zabbix agent
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    container_name: zabbix-agent
    restart: always
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-agent

volumes:
  redis_data:
  postgres_data:
